# Generated by Django 3.2 on 2021-04-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(max_length=32)),
                ('creator_nickname', models.CharField(max_length=64)),
                ('blog_content', models.CharField(max_length=1024)),
                ('creator_id', models.CharField(max_length=64)),
                ('creat_time', models.CharField(max_length=128)),
            ],
        ),
    ]
