# Generated by Django 3.2 on 2021-04-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(max_length=32)),
                ('creator_nickname', models.CharField(max_length=64)),
                ('blog_content', models.CharField(max_length=1024)),
                ('creator_id', models.CharField(max_length=64)),
                ('creat_time', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
